### PR TITLE
Adding Google blocklist, and addings tons of domains to block Youtube and Spotify

### PR DESCRIPTION
**Pull request by PoorPocketsMcNewHold**
As said, I suppose everything is either self-explanatory, or properly explain in the descriptions of each commit. 
Thanks btw for your service, I’ve been a proud user of it, for quite a while now and been using it each day.

### CODE REVIEW

**Comment by romaincointepas** [comment]
Hardcore stuff, but cool idea!

We wildcard block by default, so a list containing only parent domains would be better as it would potentially catch more stuff (ex: including `googlesyndication.com` would block all its subdomains automatically. Same with `google.com`, `withgoogle.com`, `googleapis.com`, `googleusercontent.com`, etc.). Do you think you could push this on the official repo?

**Comment by PoorPocketsMcNewHold** [comment]
Sure thing !

I'm currently in vacation, so i would be able to update the main repo as suggested.
I should be able to update it in maximum two weeks.

-------- Message d'origine --------

**Comment by PoorPocketsMcNewHold** [comment]
Done, I suppose this should make my pull request much lighter! Feel free to point me some mistake i’ve done, I’m not too common with all of theses currently.

**Comment by dimqua** [comment]
Isn't it better to block Google by IP ranges (like 35.190.247.0/24 and others) instead of domain names?

**Comment by PoorPocketsMcNewHold** [comment]
[**@dimqua**](https://github.com/dimqua) commented on [Aug 17, 2019, 8:18 PM GMT+2](https://github.com/nextdns/lists/pull/13#issuecomment-522259861 "2019-08-17T18:18:54Z - Replied by Github Reply Comments"):
> Isn't it better to block Google by IP ranges (like [35.190.247.0/24](http://35.190.247.0/24 "Linkify Plus Plus") and others) instead of domain names?
Outside of NextDNS, I think this is a pretty great idea, but would´nt this make whitelisting specific domains nor services for the users a lot more difficult? As it would need to review everything which output from the Google servers, instead of just directly letting the domains they agree upon to unblock directly.

**Comment by dimqua** [comment]
I agree. But wouldn't it make sense to expand the list of services with generic google domains, not just YouTube?

**Comment by romaincointepas** [comment]
I've updated the domains for the spotify and youtube services (https://github.com/nextdns/lists/commit/d4678c454f37a08e239564267777d449f53f2353, https://github.com/nextdns/lists/commit/501e90e5be82d7040439862d702428a8760d7e5a). Thanks!

Regarding `No G`, could you make a secondary list containing topmost-domains only? It's better for 2 reasons: it's easier to read/deal with, and it catches WAY more domains (for example, having only `googlesyndication.com` instead of all the specific `*.googlesyndication.com` domains).

**Comment by PoorPocketsMcNewHold** [comment]
Sure thing ! I´ll work on that, and update it when it´s done.

**Comment by PoorPocketsMcNewHold** [comment]
Update on that ?

**Comment by romaincointepas** [comment]
Added No G in https://github.com/nextdns/lists/commit/00eca36f6ac934da422f3720afb1eb6463b7d44c, thanks!

You could probably convert the hosts file format to a simply new line separated list of domains.
You could also clean up lots of unnecessary subdomains when the parent domain is already is the list.
You can probably also remove the IPs? We ignore them for now (never reaches DNS), and that's probably the case for anyone else using this blocklist.

For example, before:
```
#This blocklist tries to shorten down the original pihole-google list by keepin only the main domains in the list, making all the linked other domains hosted on those, be blocked as well.
#Last updated: 12-09-2019

#Google Analytics
0.0.0.0 www.googleanalytics.com
0.0.0.0 www.google-analytics.com
0.0.0.0 google-analytics.com

#Google Tag Manager
0.0.0.0 googletagmanager.com
0.0.0.0 www.googletagmanager.com
0.0.0.0 .googletagmanager.com
0.0.0.0 tagmanager.google.com
0.0.0.0 www-googletagmanager.l.google.com

#googletagservices.com
0.0.0.0 googletagservices.com
0.0.0.0 www.googletagservices.com

#Google Android
0.0.0.0 android.com
0.0.0.0 www.android.com
0.0.0.0 android-safebrowsing.google.com
0.0.0.0 android.clients.google.com

#Google DNS Servers
0.0.0.0 8.8.8.8
0.0.0.0 8.8.4.4
0.0.0.0 2001:4860:4860::8888
0.0.0.0 2001:4860:4860::8844

#Google Domains
0.0.0.0 google.ad
0.0.0.0 www.google.ad
0.0.0.0 google.ae
0.0.0.0 www.google.ae
0.0.0.0 google.com.ag
0.0.0.0 www.google.com.ag
...
```

After:
```
#This blocklist tries to shorten down the original pihole-google list by keepin only the main domains in the list, making all the linked other domains hosted on those, be blocked as well.
#Last updated: 12-09-2019

#Google Analytics
googleanalytics.com
google-analytics.com

#Google Tag Manager
googletagmanager.com
tagmanager.google.com
www-googletagmanager.l.google.com

#googletagservices.com
googletagservices.com

#Google Android
android.com
android-safebrowsing.google.com
android.clients.google.com

#Google Domains
google.ad
google.ae
google.com.ag
...
```

**Comment by PoorPocketsMcNewHold** [comment]
Thanks for the suggestions, I’ll update that right away.

**Pull request closed without merging**
