### PR TITLE
Add lists that HackeyBlock uses

### PR DESCRIPTION
**Pull request by Marnix0810**
The lists that I added will grow more fast after the end-of-support of [Marnix0810/HackeyBlock](https://github.com/Marnix0810/Hackey-Blocker).

The lists I proposed to add are:

- HackeyBlock Ad list
- HackeyKids (Hackey AdultBlock in HackeyBlock-Windows)
- HackeyPrivacy
- HackeySafety

### CODE REVIEW

**Comment by bestpika** [comment]
<https://marnix0810.wordpress.com/2019/09/06/end-of-support-for-hackeyblock/>

**Comment by Marnix0810** [comment]
@bestpika yes, the original windows desktop app will end support in 2020, but the lists will continue. They will even grow faster after the eos (end of support)

**Comment by romaincointepas** [comment]
@bestpika Can I ask why do you think those lists will grow faster after EoS of the original app (versus the expected opposite reaction, which is to stop being maintained)?

**Comment by Marnix0810** [comment]
I don't know that for sure anymore, but the whole reason that they stopped growing was because I stopped using the original app, those lists were being expanded by using them and if they missed something I added it, but I was planning on using NextDNS (and expanding the list while using NextDNS), altough for some compatibility reasons I temporarily stopped using NextDNS (which is the reason I don't know it for sure anymore).

**Comment by romaincointepas** [comment]
@Marnix0810 Got it. Could you give NextDNS another try and talk to us via the chat on our website if you encounter an issue?

I'm going to close this for now. If after using NextDNS for a bit you still think there is some value adding those lists with you as sole maintainer, we can reopen.

**Comment by Marnix0810** [comment]
Ok, thank you for your time.

**Pull request closed without merging**
